package it.ru.mail.jira.plugins.disposition;

public class ElementsXPath {
    public static String loginFrame = "//iframe[@id=\"gadget-0\"]";
    public static String loginField = "//input[@id=\"login-form-username\"]";
    public static String passwordField = "//input[@id=\"login-form-password\"]";
    public static String loginButton = "//input[@id=\"login\"]";
    public static String userMenu = "//nav[@class=\"global\"]//a/span";
    public static String issuesMenu = "//a[@id=\"find_link_drop\"]/span";
    public static String createIssue = "//a[@id=\"issues_new_issue_link_lnk\"]";
    public static String createAnotherCheckbox = "//input[@id=\"qf-create-another\"]";
    public static String createIssueSubmitButton = "//input[@id=\"create-issue-submit\"]";
    public static String createIssueSummaryField = "//input[@id=\"summary\"]";
    public static String logoutButton = "//a[@id=\"log_out\"]";
    public static String searchButton = "//input[@id=\"issue-filter-submit\"]";
    public static String sortByQueueButton = "//span[@title=\"Sort By Disposition\"]";
    public static String rowOnPos = "//td[text()=%d]";
    public static String queueKeyOnPos = "//tr[td/text()=%d]/td[@class=\"nav issuekey\"]";
    public static String allIssuesCheckbox = "//input[@name=\"all\"]";
    public static String nextButton = "(//input[@id=\"Next\"])[1]";
    public static String deleteOption = "//input[@id=\"bulk.delete.operation.name_id\"]";
    public static String confirmButton = "(//input[@name=\"Confirm\"])[1]";
    public static String addCustomFieldButton = "//a[@id=\"add_custom_fields\"]";
    public static String issueDispositionOption = "//input[@id=\"ru.mail.jira.plugins.jira-issues-disposition:issue-disposition-field_id\"]";
    public static String addCFNextButton = "//input[@id=\"nextButton\"]";
    public static String fieldNameInput = "//input[@name=\"fieldName\"]";
    public static String screenCheckboxes = "//input[@type=\"checkbox\"]";
    public static String customFieldToolsButton = "//a[@class=\"aui-dd-link cog-dd js-default-dropdown\"]";
    public static String configureFieldOption = "(//a[@class=\"aui-list-item-link\"])[1]";
    public static String deleteFieldOption = "(//a[@class=\"aui-list-item-link\"])[4]";
    public static String editJqlLink = "(//td[@class=\"fieldValueArea\"]/a)[3]";
    public static String jqlField = "//input[@id=\"jql\"]";
    public static String submitButton = "//input[@type=\"submit\"]";
    public static String selectColumnDD = "//select[@id=\"issue-nav-add-columns-column-select\"]";
    public static String addColumnButton = "//input[@id=\"issue-nav-add-columns-submit\"]";
    public static String reindexButton = "//input[@id=\"reindex-btn\"]";
    public static String hideColumnButton = "//img[@title=\"Hide column '%s'\"]";
    public static String welcomeButton = "//a[@class=\"welcome-screen-action add-project-trigger\"]";
    public static String projectNameField = "//input[@id=\"add-project-name\"]";
    public static String addProjectButton = "//input[@id=\"add-project-submit\"]";
    public static String groupNameField = "(//input[@type=\"text\"])[3]";
    public static String addGroupButton = "//input[@name=\"add_group\"]";
    public static String groupOption = "//option[@value=\"%s\"]";
    public static String addUsersToGroupInput = "//textarea[@id=\"usersToAssignStr\"]";
    public static String joinButton = "//input[@value=\"<< Join\"]";
    public static String issueToolButton = "(//td[@class=\"nav issue_actions\"]//span)[%d]";
    public static String closeOption = "(//a[@class=\"aui-list-item-link issueaction-workflow-transition\"])[1]";
    public static String closeIssueButton = "//input[@id='issue-workflow-transition-submit']";
}
